// <auto-generated />
using MVC_UI_Javascript.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_UI_Javascript.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("MVC_UI_Javascript.Models.Employee", b =>
                {
                    b.Property<int>("Employeeid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmployeeName");

                    b.Property<string>("Location");

                    b.Property<string>("Position");

                    b.HasKey("Employeeid");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
